server:
  port: 7070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/java13AuthDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: java13
    password: 123

jwt:
  secretKey: ${java13secretkey}
  audience: ${java13audience}
  issuer:   ${java13issuer}

rabbitmq:
  exchange-auth: auth-exchange
  key-register: register-key
  queue-register: register-queue
  key-mail-sender: mail-sender-key
  queue-mail-sender: mail-sender-queue
